version: '3.9'
services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore_emulator:${FIRESTORE_EMULATOR_PORT}
      - FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_SECONDS_TO_EXPIRATION=${JWT_SECONDS_TO_EXPIRATION}
