steps:
  - name: gcr.io/$PROJECT_ID/zip
    args:
      [
        "-r",
        "translate-document-cloud-function.zip",
        "index.js",
        "package.json",
        "package-lock.json",
      ]
    dir: cloud-functions/translate-document
    id: translate-document-cloud-function-zip
    waitFor: ["-"]
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "storage",
        "cp",
        "translate-document-cloud-function.zip",
        "gs://${_TRANSLATE_DOCUMENT_CLOUD_FUNCTION_SOURCE_ARCHIVE_BUCKET}/translate-document-cloud-function.zip",
        "--quiet",
      ]
    dir: cloud-functions/translate-document
    waitFor: ["translate-document-cloud-function-zip"]
  - name: gcr.io/$PROJECT_ID/terraform
    args:
      [
        "-chdir=deployment/google-cloud/terraform/environment",
        "init",
        "-backend-config=bucket=${_TFSTATE_BUCKET}",
      ]
  - name: gcr.io/$PROJECT_ID/terraform
    args:
      [
        "-chdir=deployment/google-cloud/terraform/environment",
        "apply",
        "-auto-approve",
      ]
    env:
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "TF_VAR_region=${_REGION}"
      - "TF_VAR_target_language_codes=${_TARGET_LANGUAGE_CODES}"
      - "TF_VAR_translate_document_cloud_function_source_archive_bucket=${_TRANSLATE_DOCUMENT_CLOUD_FUNCTION_SOURCE_ARCHIVE_BUCKET}"
      - "TF_VAR_translate_document_cloud_function_source_archive_object=translate-document-cloud-function.zip"
