substitutions:
  _SERVER_IMAGE_FULL: "${_SERVER_IMAGE}:${COMMIT_SHA}"
steps:
  # Server
  - id: server-docker-build
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag", "${_SERVER_IMAGE_FULL}", "."]
    dir: server
  - id: server-docker-push
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_SERVER_IMAGE_FULL}"]
    dir: server
  - id: translate-document-cloud-function-zip
    name: gcr.io/$PROJECT_ID/zip
    args: ["-r", "translate-document-cloud-function.zip", "."]
    dir: cloud-functions/translate-document
    waitFor: ["-"]
  # Translate Document Cloud Function
  - id: translate-document-cloud-function-upload
    name: gcr.io/cloud-builders/gcloud
    args:
      [
        "storage",
        "cp",
        "translate-document-cloud-function.zip",
        "gs://${_TRANSLATE_DOCUMENT_CLOUD_FUNCTION_SOURCE_ARCHIVE_BUCKET}/translate-document-cloud-function.zip",
        "--quiet",
      ]
    dir: cloud-functions/translate-document
    waitFor: ["translate-document-cloud-function-zip"]
  # Deployment
  - id: terraform-init
    name: gcr.io/$PROJECT_ID/terraform
    args:
      [
        "-chdir=deployment/google-cloud/terraform/environment",
        "init",
        "-backend-config=bucket=${_TFSTATE_BUCKET}",
      ]
  - id: terraform-apply
    name: gcr.io/$PROJECT_ID/terraform
    args:
      [
        "-chdir=deployment/google-cloud/terraform/environment",
        "apply",
        "-auto-approve",
      ]
    env:
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "TF_VAR_region=${_REGION}"
      - "TF_VAR_domain=${_DOMAIN}"
      - "TF_VAR_server_image=${_SERVER_IMAGE_FULL}"
      - "TF_VAR_translate_document_cloud_function_source_archive_bucket=${_TRANSLATE_DOCUMENT_CLOUD_FUNCTION_SOURCE_ARCHIVE_BUCKET}"
      - "TF_VAR_translate_document_cloud_function_source_archive_object=translate-document-cloud-function.zip"
